---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elasticsearch domain CW monitoring'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Elasticsearch'
      Parameters:
      - DomainName
    - Label:
        default: 'Thresholds'
      Parameters:
      - CPUUtilizationThreshold
      - MasterCPUUtilizationThreshold
      - FreeStorageSpaceThreshold
      - JVMMemoryPressureThreshold
      - MasterJVMMemoryPressureThreshold
Parameters:
  DomainName:
    Description: 'The domain name of the Elasticsearch domain that you want to monitor.'
    Type: String
  CPUUtilizationThreshold:
    Description: 'The maximum percentage of CPU resources used for data nodes in the cluster (set to -1 to disable).'
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 100
  MasterCPUUtilizationThreshold:
    Description: 'The maximum percentage of CPU resources used for master nodes in the cluster (set to -1 to disable).'
    Type: Number
    Default: 50
    MinValue: -1
    MaxValue: 100
  FreeStorageSpaceThreshold:
    Description: 'The minimum amount of available storage space in the cluster in Megabyte (set to -1 to disable).'
    Type: Number
    Default: 20480 # 20 Gigabyte in Megabyte
    MinValue: -1
  JVMMemoryPressureThreshold:
    Description: 'The maximum percentage of the Java heap used for all data nodes in the cluster (set to -1 to disable).'
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 100
  MasterJVMMemoryPressureThreshold:
    Description: 'The maximum percentage of the Java heap used for all master nodes in the cluster (set to -1 to disable).'
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 100
Conditions:
  HasCPUUtilizationThreshold: !Not [!Equals [!Ref CPUUtilizationThreshold, '-1']]
  HasMasterCPUUtilizationThreshold: !Not [!Equals [!Ref MasterCPUUtilizationThreshold, '-1']]
  HasFreeStorageSpaceThreshold: !Not [!Equals [!Ref FreeStorageSpaceThreshold, '-1']]
  HasJVMMemoryPressureThreshold: !Not [!Equals [!Ref JVMMemoryPressureThreshold, '-1']]
  HasMasterJVMMemoryPressureThreshold: !Not [!Equals [!Ref MasterJVMMemoryPressureThreshold, '-1']]
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: "cw-es-notification-topic"
  TopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Id: Id1
        Version: '2012-10-17'
        Statement:
        - Sid: Sid1
          Effect: Allow
          Principal:
            Service: 'events.amazonaws.com' # Allow CloudWatch Events
          Action: 'sns:Publish'
          Resource: !Ref Topic
        - Sid: Sid2
          Effect: Allow
          Principal:
            AWS: '*' # Allow CloudWatch Alarms
          Action: 'sns:Publish'
          Resource: !Ref Topic
          Condition:
            StringEquals:
              'AWS:SourceOwner': !Ref 'AWS::AccountId'
      Topics:
      - !Ref Topic

#### Currently, you can use the AWS CloudFormation template objects AWS::SNS::Topic and AWS::SNS::Subscription to -
#### subscribe single endpoints to SNS topics. To subscribe multiple endpoints, you have to invoke the object multiple times.

  TopicEndpointSubscription1:
    DependsOn: TopicPolicy
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: ransome_ndikum@shi.com
      Protocol: email
      TopicArn: !Ref Topic
  #TopicEndpointSubscription2:
    #DependsOn: TopicPolicy
    #Type: 'AWS::SNS::Subscription'
    #Properties:
      #Endpoint: ransome_ndikum@shi.com
      #Protocol: email
      #TopicArn: !Ref Topic
  #############################ALARMS#####################################
  StatusYellowAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "StatusYellowAlarm" ] ]
      AlarmDescription: 'Replica shards for at least one index are not allocated to nodes in a cluster.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'ClusterStatus.yellow'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Maximum
      Threshold: 1
  StatusRedAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "StatusRedAlarm" ] ]
      AlarmDescription: 'Primary and replica shards of at least one index are not allocated to nodes in a cluster.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'ClusterStatus.red'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Maximum
      Threshold: 1
  CPUUtilizationTooHighAlarm:
    Condition: HasCPUUtilizationThreshold
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "CPUUtilizationTooHighAlarm" ] ]
      AlarmDescription: 'Average CPU utilization over last 10 minutes too high.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 3
      MetricName: 'CPUUtilization'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 900
      Statistic: Average
      Threshold: !Ref CPUUtilizationThreshold
  MasterCPUUtilizationTooHighAlarm:
    Condition: HasMasterCPUUtilizationThreshold
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "MasterCPUUtilizationTooHighAlarm" ] ]
      AlarmDescription: 'Average CPU utilization over last 10 minutes too high.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 3
      MetricName: 'MasterCPUUtilization'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 900
      Statistic: Average
      Threshold: !Ref MasterCPUUtilizationThreshold
  FreeStorageSpaceTooLowAlarm:
    Condition: HasFreeStorageSpaceThreshold
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "FreeStorageSpaceTooLowAlarm" ] ]
      AlarmDescription: 'Cluster is running out of storage space.'
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'FreeStorageSpace'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Minimum
      Threshold: !Ref FreeStorageSpaceThreshold
  IndexWritesBlockedTooHighAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "IndexWritesBlockedTooHighAlarm" ] ]
      AlarmDescription: 'Cluster is blocking incoming write requests.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'ClusterIndexWritesBlocked'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 300
      Statistic: Maximum
      Threshold: 1
  JVMMemoryPressureTooHighAlarm:
    Condition: HasJVMMemoryPressureThreshold
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "JVMMemoryPressureTooHighAlarm" ] ]
      AlarmDescription: 'Average JVM memory pressure over last 10 minutes too high.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 3
      MetricName: 'JVMMemoryPressure'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 600
      Statistic: Average
      Threshold: !Ref JVMMemoryPressureThreshold
  MasterJVMMemoryPressureTooHighAlarm:
    Condition: HasMasterJVMMemoryPressureThreshold
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "MasterJVMMemoryPressureTooHighAlarm" ] ]
      AlarmDescription: 'Average JVM memory pressure over last 10 minutes too high.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'MasterJVMMemoryPressure'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 900
      Statistic: Average
      Threshold: !Ref MasterJVMMemoryPressureThreshold
  MasterNotReachableFromNodeAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "MasterNotReachableFromNodeAlarm" ] ]
      AlarmDescription: 'Master node stopped or not reachable. Usually the result of a network connectivity issue or AWS dependency problem.'
      ComparisonOperator: LessThanThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'MasterReachableFromNode'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Minimum
      Threshold: 1
  AutomatedSnapshotFailureTooHighAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "AutomatedSnapshotFailureTooHighAlarm" ] ]
      AlarmDescription: 'No automated snapshot was taken for the domain in the previous 36 hours.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'AutomatedSnapshotFailure'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Maximum
      Threshold: 1
  KMSKeyErrorAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "KMSKeyErrorAlarm" ] ]
      AlarmDescription: 'KMS customer master key used to encrypt data at rest has been disabled.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'KMSKeyError'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Maximum
      Threshold: 1
  KMSKeyInaccessibleAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "KMSKeyInaccessibleAlarm" ] ]
      AlarmDescription: 'KMS customer master key used to encrypt data at rest has been deleted or revoked its grants to Amazon ES.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'KMSKeyInaccessible'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 60
      Statistic: Maximum
      Threshold: 1
  NodesUnreachableForOneDayAlarm:
    #DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmName: !Join [ "-", [ !Ref DomainName, "NodesUnreachableForOneDayAlarm" ] ]
      AlarmDescription: 'One node in your cluster has been unreachable for one day.'
      ComparisonOperator: LessThanThreshold
      Dimensions:
      - Name: ClientId
        Value: !Ref 'AWS::AccountId'
      - Name: DomainName
        Value: !Ref DomainName
      EvaluationPeriods: 1
      MetricName: 'Nodes'
      Namespace: 'AWS/ES'
      OKActions:
      - !Ref Topic
      Period: 86400
      Statistic: Minimum
      Threshold: 1
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  StackTemplate:
    Description: 'Stack template.'
    Value: 'cf-enable-cloudwatch-monitoring-for-elasticsearch'
  StackVersion:
    Description: 'Stack version.'
    Value: '1.3.1'
